{
  "_comment": "Generated by openg2p-developer (make generate). Copied to awe/ui/public/config.json on run. Login with the dev Keycloak user (default staff/staff); AWE_ADMIN is assigned on client awe-admin-portal.",
  "keycloak": {
    "url": "{{KEYCLOAK_URL}}",
    "realm": "{{KEYCLOAK_REALM}}",
    "clientId": "awe-admin-portal"
  }
}
