# Generated AWE API runtime env — source before `uvicorn awe.main:app`
UVICORN_HOST="0.0.0.0"
UVICORN_PORT={{AWE_API_PORT}}

DB_HOST="{{POSTGRES_HOST}}"
DB_PORT={{POSTGRES_PORT}}
DB_NAME=awe
DB_USER=postgres
DB_PASSWORD="{{POSTGRES_PASSWORD}}"

CONFIG_PATH="{{AWE_CONFIG_PATH}}"

AWE__KEYCLOAK__BASE_URL="{{KEYCLOAK_URL}}"
AWE__KEYCLOAK__REALM="{{KEYCLOAK_REALM}}"
AWE__KEYCLOAK__ADMIN_CLIENT_ID=awe-admin-resolver
AWE__KEYCLOAK__ADMIN_CLIENT_SECRET="{{KEYCLOAK_AWE_RESOLVER_CLIENT_SECRET}}"
AWE__KEYCLOAK__ISSUER="{{KEYCLOAK_URL}}/realms/{{KEYCLOAK_REALM}}"
AWE__KEYCLOAK__JWKS_URL="{{KEYCLOAK_URL}}/realms/{{KEYCLOAK_REALM}}/protocol/openid-connect/certs"
AWE__KEYCLOAK__AUDIENCE=""
