G2P_BRIDGE_EXAMPLE_BANK_API_PORT={{G2P_BRIDGE_EXAMPLE_BANK_PORT}}
G2P_BRIDGE_EXAMPLE_BANK_API_DB_HOSTNAME={{POSTGRES_HOST}}
G2P_BRIDGE_EXAMPLE_BANK_API_DB_PORT={{POSTGRES_PORT}}
G2P_BRIDGE_EXAMPLE_BANK_API_DB_USERNAME=bridgeuser
G2P_BRIDGE_EXAMPLE_BANK_API_DB_PASSWORD=bridgepass
G2P_BRIDGE_EXAMPLE_BANK_API_DB_DBNAME=examplebankdb

G2P_BRIDGE_EXAMPLE_BANK_API_CELERY_BROKER_URL=redis://{{REDIS_HOST}}:{{REDIS_PORT}}/2
G2P_BRIDGE_EXAMPLE_BANK_API_CELERY_BACKEND_URL=redis://{{REDIS_HOST}}:{{REDIS_PORT}}/2
