G2P_BRIDGE_PARTNER_API_PORT={{G2P_BRIDGE_API_PORT}}
G2P_BRIDGE_PARTNER_API_DB_HOSTNAME={{POSTGRES_HOST}}
G2P_BRIDGE_PARTNER_API_DB_PORT={{POSTGRES_PORT}}
G2P_BRIDGE_PARTNER_API_DB_USERNAME=bridgeuser
G2P_BRIDGE_PARTNER_API_DB_PASSWORD=bridgepass
G2P_BRIDGE_PARTNER_API_DB_DBNAME=g2pbridgedb

G2P_BRIDGE_PARTNER_API_CELERY_BROKER_URL=redis://{{REDIS_HOST}}:{{REDIS_PORT}}/1
G2P_BRIDGE_PARTNER_API_CELERY_BACKEND_URL=redis://{{REDIS_HOST}}:{{REDIS_PORT}}/1

G2P_BRIDGE_PARTNER_API_AUTH_PROVIDER_API_URL={{KEYCLOAK_URL}}
G2P_BRIDGE_PARTNER_API_KEYCLOAK_CLIENT_ID=g2p-bridge
