G2P_BRIDGE_CELERY_WORKERS_DB_HOSTNAME={{POSTGRES_HOST}}
G2P_BRIDGE_CELERY_WORKERS_DB_PORT={{POSTGRES_PORT}}
G2P_BRIDGE_CELERY_WORKERS_DB_USERNAME=bridgeuser
G2P_BRIDGE_CELERY_WORKERS_DB_PASSWORD=bridgepass
G2P_BRIDGE_CELERY_WORKERS_DB_DBNAME=g2pbridgedb

G2P_BRIDGE_CELERY_WORKERS_CELERY_BROKER_URL=redis://{{REDIS_HOST}}:{{REDIS_PORT}}/1
G2P_BRIDGE_CELERY_WORKERS_CELERY_BACKEND_URL=redis://{{REDIS_HOST}}:{{REDIS_PORT}}/1
