G2P_BRIDGE_APP_PORT={{G2P_BRIDGE_API_PORT}}
G2P_BRIDGE_APP_HOST=0.0.0.0
G2P_BRIDGE_WORKER_TYPE=uvicorn

G2P_BRIDGE_DB_DRIVER=postgresql+asyncpg
G2P_BRIDGE_DB_HOSTNAME={{POSTGRES_HOST}}
G2P_BRIDGE_DB_PORT={{POSTGRES_PORT}}
G2P_BRIDGE_DB_USERNAME=bridgeuser
G2P_BRIDGE_DB_PASSWORD=bridgepass
G2P_BRIDGE_DB_DBNAME=g2pbridgedb

G2P_BRIDGE_CELERY_BROKER_URL=redis://{{REDIS_HOST}}:{{REDIS_PORT}}/{{G2P_BRIDGE_REDIS_DB}}
G2P_BRIDGE_CELERY_BACKEND_URL=redis://{{REDIS_HOST}}:{{REDIS_PORT}}/{{G2P_BRIDGE_REDIS_DB}}

G2P_BRIDGE_SIGNATURE_VALIDATION_ENABLED=false
G2P_BRIDGE_CRYPTO_BACKEND=local
G2P_BRIDGE_OAUTH_ENABLED=false
G2P_BRIDGE_AUTH_ENABLED=false
G2P_BRIDGE_OPENAPI_ROOT_PATH=/
