EXAMPLE_BANK_APP_PORT={{G2P_BRIDGE_EXAMPLE_BANK_PORT}}
EXAMPLE_BANK_APP_HOST=0.0.0.0
EXAMPLE_BANK_WORKER_TYPE=uvicorn

EXAMPLE_BANK_DB_DRIVER=postgresql+asyncpg
EXAMPLE_BANK_DB_HOSTNAME={{POSTGRES_HOST}}
EXAMPLE_BANK_DB_PORT={{POSTGRES_PORT}}
EXAMPLE_BANK_DB_USERNAME=bridgeuser
EXAMPLE_BANK_DB_PASSWORD=bridgepass
EXAMPLE_BANK_DB_DBNAME=examplebankdb

EXAMPLE_BANK_CELERY_BROKER_URL=redis://{{REDIS_HOST}}:{{REDIS_PORT}}/{{EXAMPLE_BANK_REDIS_DB}}
EXAMPLE_BANK_CELERY_BACKEND_URL=redis://{{REDIS_HOST}}:{{REDIS_PORT}}/{{EXAMPLE_BANK_REDIS_DB}}
EXAMPLE_BANK_CELERY_WORKER_TASK_QUEUE=example_bank_queue

EXAMPLE_BANK_SEED_TREASURY_ACCOUNT=true
EXAMPLE_BANK_TREASURY_ACCOUNT_NUMBER=1000000001
EXAMPLE_BANK_TREASURY_ACCOUNT_CURRENCY=USD
EXAMPLE_BANK_TREASURY_AVAILABLE_BALANCE=100000000
EXAMPLE_BANK_TREASURY_ACCOUNT_HOLDER_NAME="Program Treasury"
EXAMPLE_BANK_OPENAPI_ROOT_PATH=/
