STAFF_PORTAL_API_APP_HOST="0.0.0.0"
STAFF_PORTAL_API_APP_PORT={{PBMS_STAFF_API_PORT}}

# openg2p-fastapi-common reads COMMON_* for uvicorn bind (see registry staff API env)
COMMON_APP_HOST="0.0.0.0"
COMMON_APP_PORT={{PBMS_STAFF_API_PORT}}

STAFF_PORTAL_API_DB_DRIVER="postgresql+asyncpg"
STAFF_PORTAL_API_DB_USERNAME="postgres"
STAFF_PORTAL_API_DB_PASSWORD="{{POSTGRES_PASSWORD}}"
STAFF_PORTAL_API_DB_HOSTNAME="{{POSTGRES_HOST}}"
STAFF_PORTAL_API_DB_PORT={{POSTGRES_PORT}}
STAFF_PORTAL_API_DB_DBNAME="{{PBMS_BGTASK_DB_NAME}}"

STAFF_PORTAL_API_DB_USERNAME_SR="postgres"
STAFF_PORTAL_API_DB_PASSWORD_SR="{{POSTGRES_PASSWORD}}"
STAFF_PORTAL_API_DB_HOSTNAME_SR="{{POSTGRES_HOST}}"
STAFF_PORTAL_API_DB_PORT_SR={{POSTGRES_PORT}}
STAFF_PORTAL_API_DB_DBNAME_SR="{{PBMS_REGISTRY_DB_NAME}}"

STAFF_PORTAL_API_AUTH_ENABLED="false"
STAFF_PORTAL_API_OPENAPI_ROOT_PATH="/"
STAFF_PORTAL_API_CORS_ALLOW_ORIGINS='["*"]'
