BG_TASK_CELERY_BEAT_CELERY_BROKER_URL="redis://{{REDIS_HOST}}:{{REDIS_PORT}}/{{PBMS_REDIS_DB}}"
BG_TASK_CELERY_BEAT_CELERY_BACKEND_URL="redis://{{REDIS_HOST}}:{{REDIS_PORT}}/{{PBMS_REDIS_DB}}"

BG_TASK_CELERY_BEAT_PRODUCER_FREQUENCY=20
BG_TASK_CELERY_BEAT_BATCH_SIZE=500
BG_TASK_CELERY_BEAT_NO_OF_TASKS_TO_PROCESS=4
BG_TASK_CELERY_BEAT_BG_TASK_WORKER_QUEUE="bg_task_worker_queue"

BG_TASK_CELERY_BEAT_DB_DRIVER="postgresql"
BG_TASK_CELERY_BEAT_DB_USERNAME="postgres"
BG_TASK_CELERY_BEAT_DB_PASSWORD="{{POSTGRES_PASSWORD}}"
BG_TASK_CELERY_BEAT_DB_HOSTNAME="{{POSTGRES_HOST}}"
BG_TASK_CELERY_BEAT_DB_PORT={{POSTGRES_PORT}}
BG_TASK_CELERY_BEAT_DB_DBNAME="{{PBMS_BGTASK_DB_NAME}}"

BG_TASK_CELERY_BEAT_DB_USERNAME_SR="postgres"
BG_TASK_CELERY_BEAT_DB_PASSWORD_SR="{{POSTGRES_PASSWORD}}"
BG_TASK_CELERY_BEAT_DB_HOSTNAME_SR="{{POSTGRES_HOST}}"
BG_TASK_CELERY_BEAT_DB_PORT_SR={{POSTGRES_PORT}}
BG_TASK_CELERY_BEAT_DB_DBNAME_SR="{{PBMS_REGISTRY_DB_NAME}}"

BG_TASK_CELERY_BEAT_DB_USERNAME_PBMS="{{PBMS_DB_USER}}"
BG_TASK_CELERY_BEAT_DB_PASSWORD_PBMS="{{PBMS_DB_PASSWORD}}"
BG_TASK_CELERY_BEAT_DB_HOSTNAME_PBMS="{{POSTGRES_HOST}}"
BG_TASK_CELERY_BEAT_DB_PORT_PBMS={{POSTGRES_PORT}}
BG_TASK_CELERY_BEAT_DB_DBNAME_PBMS="{{PBMS_DB_NAME}}"
