BG_TASK_CELERY_WORKERS_CELERY_BROKER_URL="redis://{{REDIS_HOST}}:{{REDIS_PORT}}/{{PBMS_REDIS_DB}}"
BG_TASK_CELERY_WORKERS_CELERY_BACKEND_URL="redis://{{REDIS_HOST}}:{{REDIS_PORT}}/{{PBMS_REDIS_DB}}"

BG_TASK_CELERY_WORKERS_BATCH_SIZE=500
BG_TASK_CELERY_WORKERS_WORKER_MAX_ATTEMPTS=5
BG_TASK_CELERY_WORKERS_G2P_BRIDGE_BASE_URL="http://localhost:{{G2P_BRIDGE_API_PORT}}"

BG_TASK_CELERY_WORKERS_DB_DRIVER="postgresql"
BG_TASK_CELERY_WORKERS_DB_USERNAME="postgres"
BG_TASK_CELERY_WORKERS_DB_PASSWORD="{{POSTGRES_PASSWORD}}"
BG_TASK_CELERY_WORKERS_DB_HOSTNAME="{{POSTGRES_HOST}}"
BG_TASK_CELERY_WORKERS_DB_PORT={{POSTGRES_PORT}}
BG_TASK_CELERY_WORKERS_DB_DBNAME="{{PBMS_BGTASK_DB_NAME}}"

BG_TASK_CELERY_WORKERS_DB_DRIVER_ASYNC="postgresql+asyncpg"
BG_TASK_CELERY_WORKERS_DB_USERNAME_ASYNC="postgres"
BG_TASK_CELERY_WORKERS_DB_PASSWORD_ASYNC="{{POSTGRES_PASSWORD}}"
BG_TASK_CELERY_WORKERS_DB_HOSTNAME_ASYNC="{{POSTGRES_HOST}}"
BG_TASK_CELERY_WORKERS_DB_PORT_ASYNC={{POSTGRES_PORT}}
BG_TASK_CELERY_WORKERS_DB_DBNAME_ASYNC="{{PBMS_BGTASK_DB_NAME}}"

BG_TASK_CELERY_WORKERS_DB_USERNAME_SR="postgres"
BG_TASK_CELERY_WORKERS_DB_PASSWORD_SR="{{POSTGRES_PASSWORD}}"
BG_TASK_CELERY_WORKERS_DB_HOSTNAME_SR="{{POSTGRES_HOST}}"
BG_TASK_CELERY_WORKERS_DB_PORT_SR={{POSTGRES_PORT}}
BG_TASK_CELERY_WORKERS_DB_DBNAME_SR="{{PBMS_REGISTRY_DB_NAME}}"

BG_TASK_CELERY_WORKERS_DB_USERNAME_PBMS="{{PBMS_DB_USER}}"
BG_TASK_CELERY_WORKERS_DB_PASSWORD_PBMS="{{PBMS_DB_PASSWORD}}"
BG_TASK_CELERY_WORKERS_DB_HOSTNAME_PBMS="{{POSTGRES_HOST}}"
BG_TASK_CELERY_WORKERS_DB_PORT_PBMS={{POSTGRES_PORT}}
BG_TASK_CELERY_WORKERS_DB_DBNAME_PBMS="{{PBMS_DB_NAME}}"

BG_TASK_CELERY_WORKERS_KEYMANAGER_AUTH_ENABLED="false"
BG_TASK_CELERY_WORKERS_KEYMANAGER_API_BASE_URL=""
BG_TASK_CELERY_WORKERS_KEYMANAGER_AUTH_URL=""

# Local JWS signing for Bridge API calls (Bridge runs with signature validation disabled).
BG_TASK_CELERY_WORKERS_CRYPTO_BACKEND="local"
BG_TASK_CELERY_WORKERS_CRYPTO_SIGNING_KEY_PATH="{{PBMS_SIGNING_KEY_PATH}}"
BG_TASK_CELERY_WORKERS_CRYPTO_SIGNING_KEY_PASSWORD="{{PBMS_SIGNING_KEY_PASSWORD}}"
