REGISTRY_CELERY_WORKERS_DB_USERNAME="postgres"
REGISTRY_CELERY_WORKERS_DB_PASSWORD="{{POSTGRES_PASSWORD}}"
REGISTRY_CELERY_WORKERS_DB_HOSTNAME="{{POSTGRES_HOST}}"
REGISTRY_CELERY_WORKERS_DB_PORT={{POSTGRES_PORT}}
REGISTRY_CELERY_WORKERS_DB_DBNAME="{{REGISTRY_DB_NAME}}"

REGISTRY_CELERY_WORKERS_CELERY_BROKER_URL="redis://{{REDIS_HOST}}:{{REDIS_PORT}}/0"
REGISTRY_CELERY_WORKERS_CELERY_BACKEND_URL="redis://{{REDIS_HOST}}:{{REDIS_PORT}}/0"
REGISTRY_CELERY_WORKERS_WORKER_QUEUE="{{REGISTRY_WORKER_QUEUE}}"

REGISTRY_CELERY_WORKERS_BATCH_SIZE=2000
REGISTRY_CELERY_WORKERS_WORKER_MAX_ATTEMPTS=5

REGISTRY_CELERY_WORKERS_MINIO_ENDPOINT="{{MINIO_ENDPOINT}}"
REGISTRY_CELERY_WORKERS_MINIO_ACCESS_KEY="{{MINIO_ROOT_USER}}"
REGISTRY_CELERY_WORKERS_MINIO_SECRET_KEY="{{MINIO_ROOT_PASSWORD}}"
REGISTRY_CELERY_WORKERS_MINIO_SECURE=false
REGISTRY_CELERY_WORKERS_MINIO_BUCKET_NAME="templates"

REGISTRY_CELERY_WORKERS_MASTER_DATA_DB_DRIVER="postgresql+asyncpg"
REGISTRY_CELERY_WORKERS_MASTER_DATA_DB_USERNAME="postgres"
REGISTRY_CELERY_WORKERS_MASTER_DATA_DB_PASSWORD="{{POSTGRES_PASSWORD}}"
REGISTRY_CELERY_WORKERS_MASTER_DATA_DB_HOSTNAME="{{POSTGRES_HOST}}"
REGISTRY_CELERY_WORKERS_MASTER_DATA_DB_PORT={{POSTGRES_PORT}}
REGISTRY_CELERY_WORKERS_MASTER_DATA_DB_DBNAME="{{REGISTRY_MASTER_DATA_DB_NAME}}"

REGISTRY_CELERY_WORKERS_FUNCTIONAL_ID_GENERATION_URL="{{ID_GENERATOR_URL}}"
REGISTRY_CELERY_WORKERS_ID_GENERATION_ALLOCATION_PATH="/idgenerator/{id_type}/id"
REGISTRY_CELERY_WORKERS_ID_GENERATION_UPDATION_PATH=""
