PORT={{REGISTRY_UI_PORT}}
BACKEND_API_URL="http://localhost:{{REGISTRY_STAFF_API_PORT}}"
MASTERDATA_BACKEND_API_URL="http://localhost:{{REGISTRY_STAFF_API_PORT}}"
DEFAULT_LOCALE="en"
PARTNER_IMPORT_EXPORT_ENABLE="true"
PAGE_SIZE=10

IAM_URL="{{KEYCLOAK_URL}}"
KEYCLOAK_LOGOUT_URL="{{KEYCLOAK_URL}}/realms/staff/protocol/openid-connect/logout"
LOGIN_PROVIDER_ID="1"
APPLICATION_MNEMONIC="{{REGISTRY_UI_APP_MNEMONIC}}"
COOKIE_DOMAIN="localhost"
REDIRECT_URL="http://localhost:{{REGISTRY_UI_PORT}}"
