REGISTRY_STAFF_PORTAL_API_PORT={{REGISTRY_STAFF_API_PORT}}
REGISTRY_STAFF_PORTAL_API_APP_HOST="0.0.0.0"
REGISTRY_STAFF_PORTAL_API_APP_PORT={{REGISTRY_STAFF_API_PORT}}
REGISTRY_STAFF_PORTAL_API_DB_DRIVER="postgresql+asyncpg"
REGISTRY_STAFF_PORTAL_API_DB_USERNAME="postgres"
REGISTRY_STAFF_PORTAL_API_DB_PASSWORD="{{POSTGRES_PASSWORD}}"
REGISTRY_STAFF_PORTAL_API_DB_HOSTNAME="{{POSTGRES_HOST}}"
REGISTRY_STAFF_PORTAL_API_DB_PORT={{POSTGRES_PORT}}
REGISTRY_STAFF_PORTAL_API_DB_DBNAME="{{REGISTRY_DB_NAME}}"

REGISTRY_STAFF_PORTAL_API_MINIO_ENDPOINT="{{MINIO_ENDPOINT}}"
REGISTRY_STAFF_PORTAL_API_MINIO_ACCESS_KEY="{{MINIO_ROOT_USER}}"
REGISTRY_STAFF_PORTAL_API_MINIO_SECRET_KEY="{{MINIO_ROOT_PASSWORD}}"
REGISTRY_STAFF_PORTAL_API_MINIO_SECURE="false"
REGISTRY_STAFF_PORTAL_API_MINIO_BUCKET_NAME="default_bucket"
REGISTRY_STAFF_PORTAL_API_TEMPLATE_BUCKET_NAME="templates"

REGISTRY_STAFF_PORTAL_API_MASTER_DATA_DB_DRIVER="postgresql+asyncpg"
REGISTRY_STAFF_PORTAL_API_MASTER_DATA_DB_USERNAME="postgres"
REGISTRY_STAFF_PORTAL_API_MASTER_DATA_DB_PASSWORD="{{POSTGRES_PASSWORD}}"
REGISTRY_STAFF_PORTAL_API_MASTER_DATA_DB_HOSTNAME="{{POSTGRES_HOST}}"
REGISTRY_STAFF_PORTAL_API_MASTER_DATA_DB_PORT={{POSTGRES_PORT}}
REGISTRY_STAFF_PORTAL_API_MASTER_DATA_DB_DBNAME="{{REGISTRY_MASTER_DATA_DB_NAME}}"

REGISTRY_STAFF_PORTAL_API_AUTH_ENABLED="{{REGISTRY_AUTH_ENABLED}}"
REGISTRY_STAFF_PORTAL_API_AUTH_PROVIDER_API_URL="http://localhost:{{IAM_STAFF_PORT}}"
REGISTRY_STAFF_PORTAL_API_KEYCLOAK_CLIENT_ID="{{REGISTRY_KEYCLOAK_CLIENT_ID}}"
REGISTRY_STAFF_PORTAL_API_AUTH_REDIS_URL="redis://{{REDIS_HOST}}:{{REDIS_PORT}}/0"
REGISTRY_STAFF_PORTAL_API_REGISTRANT_AUTH_REDIS_URL="redis://{{REDIS_HOST}}:{{REDIS_PORT}}/0"

REGISTRY_STAFF_PORTAL_API_AUDIT_ENABLED="false"
REGISTRY_STAFF_PORTAL_API_OPENAPI_ROOT_PATH="/"
REGISTRY_STAFF_PORTAL_API_CORS_ALLOW_ORIGINS='["*"]'

# Approval Workflow Engine (AWE) — change request + intake approvals
REGISTRY_STAFF_PORTAL_API_AWE_ENABLED="true"
REGISTRY_STAFF_PORTAL_API_AWE_BASE_URL="http://localhost:{{AWE_API_PORT}}"
REGISTRY_STAFF_PORTAL_API_AWE_DEFAULT_CALLBACK_URL="http://localhost:{{REGISTRY_STAFF_API_PORT}}/awe/webhooks/decision"
REGISTRY_STAFF_PORTAL_API_AWE_CALLBACK_SECRET_ID="{{AWE_REGISTRY_CALLBACK_SECRET_ID}}"
REGISTRY_STAFF_PORTAL_API_AWE_CALLBACK_HMAC_SECRET="{{AWE_REGISTRY_CALLBACK_HMAC_SECRET}}"
